export const Mutations = {
  CREATE_TASK: 'CREATE_TASK',
  CREATE_COLUMN: 'CREATE_COLUMN',
  UPDATE_TASK: 'UPDATE_TASK',
  MOVE_TASK: 'MOVE_TASK',
  MOVE_COLUMN: 'MOVE_COLUMN',
  FILTER_TASK: 'FILTER_TASK'
}
